### ISSUE TITLE
Change nav menu

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/oregon-oni#10]
- Home, Titles, Map, Locations, Calendar, About (drop down) 
- Advanced Search will replace search, underline in search bar 
- About: Historical essays, Blog, K-12, CN, FAQ, Ack, Help, Contact

**Comment by jechols** [comment]
@sseymore: I need link destinations for everything in the about menu.  I think I got some of them correct (check the demo server), but let me know.

**Comment by sseymore** [comment]
FAQ: http://oregonnews.uoregon.edu/faq/ 
Ack: http://oregonnews.uoregon.edu/acknow/ 
Help: http://oregonnews.uoregon.edu/help/ 
Contact: Link to email Lib-odnp@lists.uoregon.edu

**Comment by jechols** [comment]
Okay, didn't realize those links were already in existence on our live site.  I'll copy the content over (unless it's already there in ONI)

**Comment by jechols** [comment]
The FAQ / Ack contents can be copied over; Help is already in ONI, so we'll just go with what's there and update it if necessary.

**Comment by jechols** [comment]
@sseymore This is now live on oregonnews-new

**Comment by sseymore** [comment]
https://oregonnews-new.uoregon.edu/acknow - unexpected error. Copy content from http://oregonnews.uoregon.edu/acknow/

https://oregonnews-new.uoregon.edu/faq - broken links listed below
Make a donation in support of digitizing the Journal. : https://securelb.imodules.com/s/1540/foundation/2col.aspx?sid=1540&gid=1&pgid=408&bledit=1&dids=292 
recommend titles for digitization:  mailto:Lib-odnp@lists.uoregon.edu 

All else is good!

**Comment by sseymore** [comment]
One more thing - since the nav tabs change color on rollover, can we get rid of the underlining for those links? We can keep it for accessibility if it's needed.

**Comment by jechols** [comment]
I only put it there because that seems to be how the dsc site's nav works.  I'm okay either way; just wasn't sure if we wanted consistency.  But looking at the library site, we don't even change color, so I'm not sure I'm being consistent anyway.

Make a choice and I'll get it done.

**Comment by sseymore** [comment]
Ok, thanks. I'll take the color change and not the underlining. Thank you!

**Comment by jechols** [comment]
Oops, one more thing - I'm keeping the underline for "Advanced Search".  Since it's not a clear header navigation link, it has to be visually different from nearby text, and underlining is the easiest way to make that happen.  (Colors often aren't enough).  Let me know if there's anything else, otherwise you can just close this.

**Comment by sseymore** [comment]
That's fine with me!
