### ISSUE TITLE
Put messaging on current site

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/oregon-oni#11]
Need more info on verbiage

**Comment by jechols** [comment]
@sseymore: Need you for this

**Comment by sseymore** [comment]
How about this: "Historic Oregon Newspapers is undergoing maintenance and updates. A new interface will be launched in August 2017." 

Is that too vague? We don't have a specific live date yet and I'm hesitant to announce one.

**Comment by jechols** [comment]
I don't really have a strong preference on wording, I just wanted something I didn't try to guess at :)

**Comment by jechols** [comment]
This should be addressed when https://github.com/uoregon-libraries/oregonnews/pull/53 merges, so I'm closing this ticket
