### ISSUE TITLE
Implement branding

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/oregon-oni#14]
Pull header and footer from http://dsc.uoregon.edu/ with some exceptions:

- [x] We need the new banner image
- [x] The site needs to still work at various sizes - e.g., the giant "Historic Oregon Newspapers" text should get smaller, as should the background image.
- [x] Fix the nav links to match the mockup more closely
- [x] Gray ankle L to R:
  - [x] Column 1:The library address without the T or F and with a link to the
    library homepage. Similar to: https://library.uoregon.edu/
  - [x] Nothing in column 2.
  - [x] Column 3: Give now button with our link. (grab the one we currently use)
    (this button: https://library.uoregon.edu/) Link:
    https://securelb.imodules.com/s/1540/foundation/2col.aspx?sid=1540&gid=1&pgid=408&bledit=1&dids=292
  - [x] Column 4: social media buttons and links
- [x] Footer: Black footer – keep copyright UO, ARR statement, and O logo only

**Comment by jechols** [comment]
@sseymore please clarify: for column 1 of the "ankle", do we actually want a library homepage link?  We have that in the header and again in the final part of the footer.  And neither the DSC nor UO Libraries pages have such a link in column 1.

**Comment by sseymore** [comment]
Ah, I didn't realize there would also be a link in the header. No link is fine for the ankle. 

One question though - where is the link going in the footer? I see only the uoregon.edu link.

**Comment by jechols** [comment]
Oh, right.  I was thinking of the uoregon.edu link, sorry.

But even so, we have the header link and there's no link in other sites, so unless you object, I still say no library.uoregon.edu link in the footer.

**Comment by sseymore** [comment]
I agree!

**Comment by jechols** [comment]
@sseymore this is now complete; see https://oregonnews-new.uoregon.edu/ and let me know if the footer should be fixed in any way

**Comment by sseymore** [comment]
Looks good. This link (https://oregonnews-new.uoregon.edu/acknow?) isn't work though.


Sarah E. Seymore
Digital Collections Metadata Librarian
University of Oregon Libraries
sseymore@uoregon.edu
https://oregondigital.org/catalog/
http://oregonnews.uoregon.edu/
________________________________

**Comment by jechols** [comment]
@sseymore - check again

**Comment by sseymore** [comment]
?Looks good!?


Sarah E. Seymore
Digital Collections Metadata Librarian
University of Oregon Libraries
sseymore@uoregon.edu
https://oregondigital.org/catalog/
http://oregonnews.uoregon.edu/
________________________________
