### ISSUE TITLE
Correct and load batches with errors

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/oregon-oni#15]
- Nyssa: Need to move papers from 1910 - January 21, 1937 to The Gate City Journal sn99063862.
  - Bad batches to be removed:
    - batch_nyssapubliclibrary_20161229ProudBlancmange_ver01
    - batch_nyssapubliclibrary_20170302MarbleDracaenaeHarvestingSunflowers_ver01
  - Good batches to load:
    - batch_nyssapubliclibrary_20170717ObsidianXiangliuBehindSunflowers_ver01
    - batch_nyssapubliclibrary_20170717BronzeKubikajiriPlantingPoisonOak_ver01
- Medford: change LCCN from 97071090 to sn97071090 for these batches:
  - batch_oru_hufnagel_ver01
  - batch_oru_iraryan_ver01
  - batch_oru_jones_ver01
- The Cottage Grove Sentinel 1916/2016 problem: both of these should be 1916 - http://oregonnews.uoregon.edu/lccn/sn96088073/2016-12-07/ed-1/ and http://oregonnews.uoregon.edu/lccn/sn96088073/2016-12-21/ed-1/
  - batch_oru_20170302JadeOrcoMammanSurroundedByStrawberries_ver01
- Polk Itemizer 1903/1908 issue: http://oregonnews.uoregon.edu/lccn/sn94049693/1903-10-01/ed-1/seq-1/ is labeled as 1903 and should be 1908.
  - batch_dallaspubliclibrary_20170104BronzeManananggalPlantingSunflowers_ver01
- Bohemia Nugget 12-26-1906 wrong date: http://oregonnews.uoregon.edu/lccn/sn96088074/1906-12-27/ed-1/ This should be the 26th. 
  - batch_oru_november_2_ver01

Subtasks:

- [x] Create fixed Nyssa batches
- [x] Ingest fixed Nyssa batches into new system
- [x] Fix Medford XMLs and PDFs
  - [x] Run batch_oru_hufnagel_ver01 through batch LCCN fixer
  - [x] Run batch_oru_iraryan_ver01 through batch LCCN fixer
  - [x] Run batch_oru_jones_ver01 through batch LCCN fixer
  - [x] Copy hufnagel to lib mount as _ver02
  - [x] Copy iraryan to lib mount as _ver02
  - [x] Copy jones to lib mount as _ver02
  - [x] Ingest hufnagel ver02
  - [x] Ingest iraryan ver02
  - [x] Ingest jones ver02
  - [x] Create XML-fixing script for the Dark Archive "patch" that runs the fixer code and automates (or at least carefully details) the _ver02 suffix and removal of _ver01 files; because of the LCCN directories, we can't just replace these live
- [x] Fix Cottage Grove Sentinel (two issues - incorrect century)
  - [x] Create script for the Dark Archive "patch"
  - [x] Duplicate batch in mount to _ver02
  - [x] Ingest fixed batch
- [x] Fix Polk Itemizer (one issue - bad date)
  - [x] Create script for the Dark Archive "patch"
  - [x] Duplicate batch in mount to _ver02
  - [x] Ingest fixed batch
- [x] Fix Bohemia Nugget (one issue - bad date)
  - [x] Create script for the Dark Archive "patch"
  - [x] Duplicate batch in mount to _ver02
  - [x] Ingest fixed batch

**Comment by jechols** [comment]
Updated the ticket to break down every single mini-task I can think of

**Comment by jechols** [comment]
Medford batches will be getting fixed via https://github.com/uoregon-libraries/batch-lccn-fixer

**Comment by jechols** [comment]
Adding a new task for the dark archive nyssa batch removal; that's not something that should hold up go-live

**Comment by jechols** [comment]
@sseymore: When time permits, please verify all the batch problems are corrected on oregonnews-new.  Once you have verified, we can close this issue.

**Comment by sseymore** [comment]
Thanks, Jeremy!

Nyssa batches are correct
Medford sn is correct
Cottage Grove, Polk, and Nugget dates are correct

!!!
