### ISSUE TITLE
Get wording for the homepage

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/oregon-oni#16]
Right now it's just placeholder text.  What should it be?

Latest UI:

![oni-home](https://user-images.githubusercontent.com/2157974/29223203-96fcbcf0-7e7a-11e7-96ca-2e6e49a031db.png)

**Comment by sseymore** [comment]
Welcome to Historic Oregon Newspapers. On this site you can search and access complete content for historic Oregon newspapers that have been digitized as part of the Oregon Digital Newspaper Program (ODNP). ODNP is committed to providing free online access to historic Oregon newspapers. This is made possible with the [support](http://oregonnews.uoregon.edu/acknow/) of federal and state grants, the UO Libraries, and through private donations. [Become a partner or contribute](http://library.uoregon.edu/digitalscholarship/digital-collections/contribute).

**Comment by jechols** [comment]
@sseymore This is ready for QA

**Comment by sseymore** [comment]
Looks great. You can close it.


-Sarah


Sarah E. Seymore
Digital Collections Metadata Librarian
University of Oregon Libraries
sseymore@uoregon.edu
https://oregondigital.org/catalog/
http://oregonnews.uoregon.edu/
________________________________

**Comment by sseymore** [comment]
?Actually, that support link is broken - see other ticket. Sorry to have to use email.


Sarah E. Seymore
Digital Collections Metadata Librarian
University of Oregon Libraries
sseymore@uoregon.edu
https://oregondigital.org/catalog/
http://oregonnews.uoregon.edu/ ?
________________________________

**Comment by jechols** [comment]
Okay, I believe I see the problem.  I'll let you know when you can check again.

**Comment by jechols** [comment]
@sseymore - check again

**Comment by sseymore** [comment]
?Looks good!


Sarah E. Seymore
Digital Collections Metadata Librarian
University of Oregon Libraries
sseymore@uoregon.edu
https://oregondigital.org/catalog/
http://oregonnews.uoregon.edu/
________________________________
