### ISSUE TITLE
Figure out customized help page

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/oregon-oni#18]
Switching to an ONI-based system means we lose some of our customized help items.  We can copy them back as-is if we want, but as ONI and chronam diverge more and more, the links, videos, etc. will become less and less relevant.

We will need to figure out how to provide the same level of help we currently have, but within the confines of the new system.

**Comment by sseymore** [comment]
Carolina will work on the tutorials so I will also get input from her.

**Comment by jechols** [comment]
@sseymore Assigning just to you for now, since I don't have any action I can take here.  When you have stuff for me, let me know and I'll take over the ticket again.

**Comment by sseymore** [comment]
Adding another problem. There is documentation on the Search page for proximity searching but that has been replaced with Words Near Each Other field that searches within the default 5 words near each other. Needs to be documented.

**Comment by jechols** [comment]
@sseymore Sounds like other ONI stakeholders are okay with getting that field back on the form, so I'm looking into that.  Then documentation doesn't have to be fixed (or at least not for this issue), *and* we haven't lost a feature from pre-upgrade.

**Comment by sseymore** [comment]
Carolina has created a LibGuide in place of the Help page: https://researchguides.uoregon.edu/oregon-news

Please update the Help link to direct to this guide. I think we can then close this issue. Thank you!

**Comment by sseymore** [comment]
@jechols can you update this link? Thank you!

**Comment by jechols** [comment]
Argh, sorry, lost track of this when it was deemed low-priority.  On it.
