### ISSUE TITLE
Revisit home page content

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/oregon-oni#19]
Some of the static content could be made more dynamic.  The page count, for instance, could be precise, or it could be rounded to say something like "about 900,000 pages".  The year range, as well, should probably not be static, as that'll become incorrect relatively soon and is very easy to pull from the data.

**Comment by jechols** [comment]
Per yesterday's conversation I'll take a look at this soon and see if it is indeed easy.  @sseymore did you want a precise page count (e.g., "906278 pages") or some kind of rounding ("Over 900,000 pages" / "nearly a million pages" / etc)?

**Comment by sseymore** [comment]
Look into it and see what's easier. I like rounding but if the precise page count is less complicated, let's do that.

**Comment by jechols** [comment]
I suspect rounding won't be too bad, but I'll do whatever takes under an hour :)

Removing you from the assignees as I think I have all the info I need to get moving!
