### ISSUE TITLE
Fix advanced search accessibility

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/oregon-oni#23]
See https://github.com/open-oni/open-oni/issues/294 - this needs to be handled in our theme if we can't get it into core ASAP.

**Comment by sseymore** [comment]
I see that you added info about the date spans, ctrl/cmd functionality, and got rid of the state info - looks good to me!

**Comment by jechols** [comment]
Reopening until we get this into core or else copy it locally.  But the change is "done" per your approval above, so once we figure out where the code will live, this can be closed.
