### ISSUE TITLE
OCR highlighting disappearing

### ISSUE THREAD

**Issue by sseymore** [uoregon-libraries/oregon-oni#34]
Search for "apples" : https://oregonnews.uoregon.edu/search/pages/results/?rows=20&searchType=basic&proxtext=apples

Choose  third result: https://oregonnews.uoregon.edu/lccn/sn83009939/1911-08-09/ed-1/seq-5/#index=2&rows=20&proxtext=apples&searchType=basic&sequence=0&words=apple+APPLE+Apple+Apples+apples+APPLES&page=1

Some of the text selection highlighting disappears after selecting the page.

**Comment by jechols** [comment]
Updated your report to point to the live host now that oregonnews-new is no more

**Comment by jechols** [comment]
This is due to the core bug, https://github.com/open-oni/open-oni/issues/246.

(We already knew this, just attaching it here so I can close both easily)

**Comment by jechols** [comment]
I've "fixed" this via a "hack it live" approach.  The core bug is fixed in ONI, but I want to leave this ticket open until that merges so that I can tag a new release and pin production to it properly.

**Comment by jechols** [comment]
Done - ready for QA

**Comment by sseymore** [comment]
My example above worked! Thank you!
