### ISSUE TITLE
Did we lose image attribution?

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/oregon-oni#37]
I thought we had this on pages, and I'm not seeing it for example on https://oregonnews.uoregon.edu/lccn/sn96088073/1909-09-24/ed-1/seq-1/.  It does appear to be in the page's metadata, though:

        <meta property="og:description" content="Cottage Grove sentinel. (Cottage Grove, Or.) 1909-current, September 24, 1909, Image 1, brought to you by University of Oregon Libraries; Eugene, OR, and the National Digital Newspaper Program." />

**Comment by jechols** [comment]
@lsat12357 - am I nuts or did this info used to show up on the pages?

**Comment by lsat12357** [comment]
Well, you’re nuts, but that’s a separate issue.
We did have attribution info, based from the organization? code that we sometimes were manually adding in the database.

**Comment by jechols** [comment]
Okay, I'll see about fixing this then

**Comment by jechols** [comment]
There's now a PR for ONI that will fix this: https://github.com/open-oni/open-oni/pull/306
