### ISSUE TITLE
Wrong date/rebatch

### ISSUE THREAD

**Issue by sseymore** [uoregon-libraries/oregon-oni#40]
https://oregonnews.uoregon.edu/lccn/sn88087070/2015-02-15/ed-1/seq-1/

Should be 2015-02-25.

**Comment by jechols** [comment]
Batch: batch_oru_20160627DespairingFlan_ver01

**Comment by jechols** [comment]
Purged the bad one, script-fixed it, and am loading the fix.  In about 20-30 minutes it should be ready to verify

**Comment by jechols** [comment]
Had a hiccup earlier, but this is now fixed!  https://oregonnews.uoregon.edu/lccn/sn88087070/2015-02-25/ed-1/
