### ISSUE TITLE
The Umpqua weekly gazette page not showing

### ISSUE THREAD

**Issue by sseymore** [uoregon-libraries/oregon-oni#42]
https://oregonnews.uoregon.edu/lccn/sn84022684/

Unexpected Error
has encountered an unexpected error while processing your request. The details of this error have been logged, and our troubleshooting specialists will be notified. We apologize for any inconvenience.

**Comment by jechols** [comment]
This is fixed in ONI core, assuming it gets merged

**Comment by jechols** [comment]
This is now on staging and merged into core

**Comment by sseymore** [comment]
Live in staging. Can be merged!
