### ISSUE TITLE
Filtering/facet bug in Advanced search

### ISSUE THREAD

**Issue by sseymore** [uoregon-libraries/oregon-oni#43]
Splitting this from #32 

Example:

Doing an advanced keyword search on one title and choosing an option in the Sort drop down on the results page and then choosing "Refine Search" is losing the newspaper selection.

Example: Do a search for "switzler" in East Oregonian and get 405 results. Choose Date in Sort and Refine Search. All titles appear, not just East Oregonian.

I think this might be happening only when certain titles are selected.

**Comment by jechols** [comment]
Related problem: using the "jump to page" functionality seems to cause *all* filters to be reset.

**Comment by jechols** [comment]
My mistake: "jump to page" clears some filters, but not all.  And the problem it has seems to be separate from the filter loss from clicking on "Refine Search".

**Comment by jechols** [comment]
Problem #1: The titles are simply not persisted at all.  The key used in queries is "lccn", but the key used when trying to persist the filters is "titles".

Problem #2: We can have multiple titles selected, but the HTML assumes only one will be.  So even after fixing problem #1, we have broken filtering.

**Comment by jechols** [comment]
And of course confusing the matter: the hidden fields which persist the search appear to be simply wrong a lot of the time.  Stuff that doesn't appear anywhere in the app is in the hidden field list.

I think fixing this will require rebuilding all these hidden fields, and doing so separately for the "jump to page" area and the "refine search" area.  Maybe combining the two forms would help, but that may be a huge pain.

**Comment by jechols** [comment]
This is now on staging (though awaiting code review in ONI core)

**Comment by sseymore** [comment]
I re-tried the"switzler" refining/sorting example above and jump to page refinement and they both worked. Please let me know when merged. Thank you!
