### ISSUE TITLE
Reorder top of Advanced Search page

### ISSUE THREAD

**Issue by sseymore** [uoregon-libraries/oregon-oni#50]
On the Advanced Search page, the Search Terms section should be moved above the Proximity Search section. The order would be Search Terms, Proximity Search, and then Limit By. We got some good feedback about the confusion/usability on this page from UX testing. 
 
![untitled](https://user-images.githubusercontent.com/7328774/35346906-6c45923e-00e8-11e8-82c9-1848be69f9f5.png)

**Comment by jechols** [comment]
Closing this - this is a core ONI fix so we don't need to track it in our theme
