### ISSUE TITLE
Figure out an accessible calendar

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/oregon-oni#7]
Default calendar is not very accessible, especially the dropdowns.

Notes:

- For the calendar – have 2 different calendars: Have both all titles and a calendar for each titles
  - For all titles: Have single colors for issues/titles on that day; click
    through instead of drop down to titles list with links to the issues
  - For single titles: Have a calendar with single and mult ed colors and "*" or
    something else to designate the mult. Ed. Click through to mult. Ed. List
    page. Direct link to single ed.

**Comment by jechols** [comment]
This is related to https://github.com/open-oni/open-oni/issues/287

**Comment by jechols** [comment]
If this can't be done prior to go-live, it needs to be our #1 priority in the "post-go-live fixes" milestone, so I'm adding it to that one just in case.

**Comment by jechols** [comment]
(oops - you can't have two milestones; set back to go-live)

**Comment by jechols** [comment]
@sseymore Check out the calendar on oregonnews-new.  I'm sure we'll want to discuss my choice of link colors and such, but at least we have something now.

**Comment by sseymore** [comment]
Looks great. Few things:

Do we need to indicate if there are multiple titles per day? I think I link to take someone to the page with the list of titles should suffice? I don't like the *.

For days with single issues, the padding to the right is a little much and awkward- can that be fixed?

Do we need to have the number of issues per year listed next to the year on the dropdown?

Link colors and everything else is fine.
