### ISSUE TITLE
Vernonia Voice MARC will need to be reloaded

### ISSUE THREAD

**Issue by sseymore** [uoregon-libraries/oregon-oni#74]
https://oregonnews.uoregon.edu/lccn/2018260012/ 

Publisher requested to have the landing page updated, so asking Rebecca to update the MARC and @jechols to correct online. However, this will be blown away one day and we will need to remember to load new MARC record when that happens. This ticket is for tracking this issue.

**Comment by jechols** [comment]
Removed myself from assignee list - when you give me MARC I can load it directly and put it into the repo that holds custom MARC records. Until then, though, there's no action I can take here.

**Comment by jechols** [comment]
New MARC loaded and stored in our repo so we'll load it if we ever have to do a full refresh (many of the our titles rely on custom marc records we've made, so loading that repo's marc is a requirement for a full batch refresh)
